name: Deploy Lambda
on:
  push:
    branches:
    - master   

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest 
    steps:
    #Using versioned actions 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:  
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: npm install
        working-directory: ./lambda_bot
        env:
          CI: true
        run: |
          npm ci 
      - name: deploy
        working-directory: ./lambda_bot
        run: |
          zip -r deploy.zip ./*
          aws lambda update-function-code --function-name=discord --zip-file=fileb://deploy.zip 